[build]
  publish = "public/"
  command = "npm run build"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

[[plugins]]
     # Installs the Emails Plugin
     package = "@netlify/plugin-emails"